### ISSUE TITLE
Instructions not working

### ISSUE THREAD

**Issue by thestumonkey** [Blucknote/anytype-api#3]
I can't seem to get this working in or out of docker by following the instructions
- When I try to call a command, I'm expecting it to ask for the auth
- I'm a bit confused on why there's a fastMCP as well as a fastAPI server?  Then there's seemingly 2 versions of the client, anytype.py and api_client?  Can you explain the project structure?
- There's no explanation on how to get the APP_KEY or the SESSION_TOKEN.

 + Exception Group Traceback (most recent call last):
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
anytype-api  |   |     result = await app(  # type: ignore[func-returns-value]
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
anytype-api  |   |     return await self.app(scope, receive, send)
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
anytype-api  |   |     await self.middleware_stack(scope, receive, send)
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
anytype-api  |   |     raise exc
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
anytype-api  |   |     await self.app(scope, receive, _send)
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
anytype-api  |   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
anytype-api  |   |     raise exc
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
anytype-api  |   |     await app(scope, receive, sender)
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 714, in __call__
anytype-api  |   |     await self.middleware_stack(scope, receive, send)
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 734, in app
anytype-api  |   |     await route.handle(scope, receive, send)
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
anytype-api  |   |     await self.app(scope, receive, send)
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
anytype-api  |   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
anytype-api  |   |     raise exc
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
anytype-api  |   |     await app(scope, receive, sender)
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
anytype-api  |   |     response = await f(request)
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/mcp/server/fastmcp/server.py", line 431, in handle_sse
anytype-api  |   |     async with sse.connect_sse(
anytype-api  |   |   File "/usr/local/lib/python3.10/contextlib.py", line 217, in __aexit__
anytype-api  |   |     await self.gen.athrow(typ, value, traceback)
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/mcp/server/sse.py", line 123, in connect_sse
anytype-api  |   |     async with anyio.create_task_group() as tg:
anytype-api  |   |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 772, in __aexit__
anytype-api  |   |     raise BaseExceptionGroup(
anytype-api  |   | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)

**Comment by thestumonkey** [comment]
Ok, that is clearer now on what I need to do, but still encountering an error.
- started docker server
- started uvicorn
- performed challenge and received ID + code
- Added code plus ID into the auth/token endpoint
- Receive error 500 from the anytype local server. 'http://localhost:31009/v1/auth/token?challenge_id=xxxxxxxx&code=yyyyy'
File "/Users/stu/repos/chakra/crown-chakra/anytype-api/app/routers/auth.py", line 36, in get_token
    return await client.get_token(code, challenge_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stu/repos/chakra/crown-chakra/anytype-api/app/clients/anytype.py", line 105, in get_token
    return TokenResponse(**result)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stu/repos/chakra/crown-chakra/anytype-api/.venv/lib/python3.11/site-packages/pydantic/main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for TokenResponse
session_token

It looks like the auth has changed to just have an API_KEY?  https://developers.anytype.io/docs/reference/2025-05-20/create-auth-challenge

**Comment by Blucknote** [comment]
Should work now

**Comment by thestumonkey** [comment]
I pulled your latest, and I made a PR to fix a few things.  Ironically the app now has an API_key generation in it.
Using the key, I'm trying to list my spaces using the inspector.

I'm still getting errors though:

anytype-api  | 2025-05-28 13:10:16,446 - mcp.server.lowlevel.server - INFO - Processing request of type CallToolRequest
anytype-api  | 2025-05-28 13:10:16,446 - mcp.server.lowlevel.server - DEBUG - Dispatching request of type CallToolRequest
anytype-api  | 2025-05-28 13:10:16,447 - app.clients.anytype - INFO - {'Content-Type': 'application/json'}
anytype-api  | 2025-05-28 13:10:16,447 - app.clients.anytype - INFO - http://127.0.0.1:31009
anytype-api  | 2025-05-28 13:10:16,447 - app.clients.anytype - INFO - <tokenxxxxxxxxx>
anytype-api  | 2025-05-28 13:10:16,447 - app.helpers.api - DEBUG - Getting endpoint: getSpaces with params: {}
anytype-api  | 2025-05-28 13:10:16,447 - app.helpers.api - DEBUG - Formatted endpoint: /v1/spaces
anytype-api  | 2025-05-28 13:10:16,447 - app.helpers.api - INFO - Making API request: GET /v1/spaces
anytype-api  | 2025-05-28 13:10:16,447 - app.helpers.api - DEBUG - Request details - Headers: {'Content-Type': 'application/json', 'accept': 'application/json', 'Authorization': 'Bearer <tokenxxxxxxxxx>'}, Data: None, Params: {'limit': 100, 'offset': 0}
anytype-api  | 2025-05-28 13:10:16,468 - httpcore.connection - DEBUG - connect_tcp.started host='127.0.0.1' port=31009 local_address=None timeout=30.0 socket_options=None
anytype-api  | 2025-05-28 13:10:16,469 - httpcore.connection - DEBUG - connect_tcp.failed exception=ConnectError(OSError('All connection attempts failed'))
anytype-api  | 2025-05-28 13:10:16,469 - app.helpers.api - ERROR - API request failed: GET /v1/spaces - All connection attempts failed (0.02s)
anytype-api  | Traceback (most recent call last):
anytype-api  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
anytype-api  |     yield
anytype-api  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
anytype-api  |     resp = await self._pool.handle_async_request(req)
anytype-api  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 256, in handle_async_request
anytype-api  |     raise exc from None
anytype-api  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request
anytype-api  |     response = await connection.handle_async_request(
anytype-api  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
anytype-api  |     raise exc
anytype-api  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 78, in handle_async_request
anytype-api  |     stream = await self._connect(request)

**Comment by thestumonkey** [comment]
Success!
The issue was that in the .env file I needed to put ANYTYPE_API_URL=http://host.docker.internal:31009
This was because I was starting using docker compose and therefire didn't use --network host
